### content configuration ###
title:       "Fabio Ferreira"
keywords:    "research, fabio ferreira, ferreira, karlsruhe, kit, deep learning, computer vision, machine learning"
description: ""
source_link: "https://ferreirafabio.github.io"
baseurl: "/"
google_analytics_key: UA-87133106-1
markdown: kramdown
tracking_id: UA-87133106-1

sass:
    style: compressed
    sass_dir: _sass




